# CI/CD Pipeline for Gatsby/TS project, in GitHub Actions

# Test -> Build -> Deploy

# Triggers
on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
# CONFIGURE PIPELINE - to allow git-tracked logic for Jobs if/when to run
# note: if in Jobs here, cannot access env context (can the vars)
# can retire this Job if all ifs leverage vars for reading Top-Level overrides
  pipe:
    uses: ./.github/workflows/pipe_config.yml
    with:
      UNIT_TESTS_ON: false  # shutdown unit-tests
      ALLOW_LINT_TO_FAIL: true
      # LINT_ON: false  # shutdown lint
      # DEPLOY_ON: true  # force deployment

      # BUILD_ON: ${{ vars.BUILD_ON }}
      # E2E_TESTS_ON: ${{ vars.E2E_TESTS_ON }}

### UNIT TEST ###
  test:
    needs: pipe
    if: always() && ( needs.pipe.outputs.UNIT_TESTS_ON == 'true' || ( needs.pipe.outputs.UNIT_TESTS_ON == '' && needs.pipe.result == 'success' ) )
    uses: ./.github/workflows/test.yml
    with:
      pipe_config: ${{ toJson(needs.pipe.outputs) }}

# HOST COVERAGE Results
  codecov:
    needs: test
    uses: ./.github/workflows/codecov.yml
    # as long as test was triggered, we run codecov. both when Test PASSed or FAILed
    if: always() && ${{ !contains(fromJSON('["skipped", "cancelled"]'), needs.test.result) }}
    with:
      coverage_ci_artifact: ${{ needs.test.outputs.COVERAGE_ARTIFACT }}
      file_prefix: clover
    secrets:
      # leverages repository secret CODECOV_TOKEN
      CODECOV_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

  lint:
    needs: pipe
    if: always() && ( needs.pipe.outputs.LINT_ON == 'true' || ( needs.pipe.outputs.LINT_ON == '' && needs.pipe.result == 'success' ) )
    uses: ./.github/workflows/lint.yml
    with:
      pipe_config: '{"ALLOW_LINT_TO_FAIL": "${{ needs.pipe.outputs.ALLOW_LINT_TO_FAIL }}"}'


## BUILD MINIFIED BUNDLE
  gatsby:
    needs: test
    if: always() && ( needs.pipe.outputs.BUILD_ON == 'true' || ( needs.pipe.outputs.BUILD_ON == '' && ( needs.pipe.outputs.DEPLOY_ON == 'true' || needs.test.result == 'success' ) ) )
    # TODO rename as below, for current solutoin to have better semantics
    # if: always() && ( needs.pipe.outputs.FORCE_BUILD == 'true' || ( needs.pipe.outputs.FORCE_BUILD == '' && needs.test.result == 'success' ) )

    # ALT SOLUTION:
    # if: always() && needs.pipe.outputs.BUILD_ON == 'true' \
    #  && ( needs.pipe.outputs.FORCE_BUILD == 'true' || needs.test.result == 'success' )

    # TODO: support different logic: allow Pass, and allow Skipped policies

    uses: ./.github/workflows/build-bundle.yml
    with:
      ci_artifact: web_bundle

### E2E TEST ###
  e2e:
    needs: [gatsby]
    if: always() && ( needs.pipe.outputs.E2E_TESTS_ON == 'true' || ( needs.pipe.outputs.E2E_TESTS_ON == '' && success() ) )
    uses: ./.github/workflows/e2e-test.yml
    with:
      website_artifact: web_bundle

# Test Web Bundle
  test_bundle:
    needs: gatsby
    uses: ./.github/workflows/test-bundle.yml
    with:
      bundle_ci_artifact: web_bundle
      bundle_size: ${{ needs.gatsby.outputs.BUNDLE_SIZE }}
      bundle_size_acceptance: 3

  signal_deploy:
    needs: [test_bundle, e2e]
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/signal-deploy.yml
    with:
      main_branch: main
      release_branch: release

  # Deploy Web Bundle
  deploy:
    # if DEPLOY_ON override boolean switch is set:
    # - true  --> Deployment WILL happen
    # - false --> Deployment will NOT happen

    # if boolean switch NOT SET then implicit default policy condition must be met:
    # - previous Jobs must succeed and signal_deploy.outputs.AUTOMATED_DEPLOY == 'true'
    needs: [signal_deploy]
    if: always() && ( needs.pipe.outputs.DEPLOY_ON == 'true' || ( needs.pipe.outputs.DEPLOY_ON == '' && needs.pipe.result == 'success' && needs.signal_deploy.outputs.AUTOMATED_DEPLOY == 'true' ) )

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    uses: ./.github/workflows/deploy.yml
    with:
      # map prod: s3 and test: github-pages
      environment: ${{ needs.signal_deploy.outputs.ENVIRONMENT_NAME == 'PROD_DEPLOYMENT' && 's3' || needs.signal_deploy.outputs.ENVIRONMENT_NAME == 'TEST_DEPLOYMENT' && 'github-pages' || 'unsupported-environment' }}
      website_artifact: web_bundle
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
