# CI/CD Pipeline for Gatsby/TS project, in GitHub Actions

# Test -> Build -> Deploy

# Triggers
on:
  push:
    branches:
      - "*"
    tags:
      - v*

env:

  ##### Top Level overrides - JOB ON/OFF SWITCHES #####
  UNIT_TESTS_ON: ""
  E2E_TESTS_ON: "true"
  LINT_ON: "true"
  BUILD_ON: "true"
  PUBLISH_ON: "true"
  DEPLOY_ON: "true"
  ### true for rest of logic to takeover ########

  #### 2nd Level overrides ####
  ALWAYS_LINT: "false"
  ALWAYS_BUILD: "false"

  ## Pipe Settings ##
  ALLOW_LINT_TO_FAIL: "true"

jobs:
  pipe_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Pipeline
        id: set_pipe_config
        run: chmod +x .github/set_env.sh && .github/set_env.sh
    outputs:
      # Output Top Level overides
      UNIT_TESTS_ON: ${{ steps.set_pipe_config.outputs.UNIT_TESTS_ON }}
      E2E_TESTS_ON: ${{ steps.set_pipe_config.outputs.E2E_TESTS_ON }}
      LINT_ON: ${{ steps.set_pipe_config.outputs.LINT_ON }}
      PUBLISH_ON: ${{ steps.set_pipe_config.outputs.PUBLISH_ON }}
      DEPLOY_ON: ${{ steps.set_pipe_config.outputs.DEPLOY_ON }}

      # Pipeline Configuration
      ALLOW_LINT_TO_FAIL: ${{ steps.set_pipe_config.outputs.ALLOW_LINT_TO_FAIL }}

### UNIT TEST ###
  test:
    needs: pipe_config
    if: always() && ( needs.pipe_config.outputs.UNIT_TESTS_ON == 'true' || ( needs.pipe_config.outputs.UNIT_TESTS_ON == '' && needs.pipe_config.result == 'success' ) )
    uses: ./.github/workflows/test.yml
    with:
      pipe_config: ${{ toJson(needs.pipe_config.outputs) }}

  lint:
    needs: pipe_config
    if: needs.pipe_config.outputs.LINT_ON == 'true'
    uses: ./.github/workflows/lint.yml
    with:
      pipe_config: '{"ALLOW_LINT_TO_FAIL": "${{ needs.pipe_config.outputs.ALLOW_LINT_TO_FAIL }}"}'

# COVERAGE HOST
  codecov:
    needs: test
    uses: ./.github/workflows/codecov.yml
    # as long as test was triggered, we run codecov. both when Test PASSed or FAILed
    if: always() && ${{ !contains(fromJSON('["skipped", "cancelled"]'), needs.test.result) }}
    with:
      coverage_ci_artifact: ${{ needs.test.outputs.COVERAGE_ARTIFACT }}
      file_prefix: clover
    secrets:
      # leverages repository secret CODECOV_TOKEN
      CODECOV_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

## BUILD MINIFIED BUNDLE
  gatsby:
    needs: test
    # TODO: add need test and allow bypass with policy
    uses: ./.github/workflows/build-bundle.yml
    # if: always()
    with:
      ci_artifact: web_bundle

### E2E TEST ###
  e2e:
    needs: [pipe_config, gatsby]
    if: needs.pipe_config.outputs.E2E_TESTS_ON == 'true'
    uses: ./.github/workflows/e2e-test.yml
    with:
      website_artifact: web_bundle

# Test Web Bundle
  test_bundle:
    needs: gatsby
    uses: ./.github/workflows/test-bundle.yml
    with:
      bundle_ci_artifact: web_bundle
      bundle_size: ${{ needs.gatsby.outputs.BUNDLE_SIZE }}
      bundle_size_acceptance: 3

  signal_deploy:
    needs: [test_bundle, e2e]
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/signal-deploy.yml
    with:
      main_branch: main
      release_branch: release

  # Deploy Web Bundle
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: [pipe_config, signal_deploy]
    if: ${{ needs.pipe_config.outputs.DEPLOY_ON == 'true' && needs.signal_deploy.outputs.AUTOMATED_DEPLOY == 'true' }}
    uses: ./.github/workflows/deploy.yml
    with:
      # map prod: s3 and test: github-pages
      environment: ${{ needs.signal_deploy.outputs.ENVIRONMENT_NAME == 'PROD_DEPLOYMENT' && 's3' || needs.signal_deploy.outputs.ENVIRONMENT_NAME == 'TEST_DEPLOYMENT' && 'github-pages' || 'unsupported-environment' }}
      website_artifact: web_bundle
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

  # test_dockerized:
  #   # needs caching to compete in speed with setup-node cache
  #   # INVESTIGATE how to combine cache and docker images
