name: 'Deploy Web Bundle to S3'

on:
  workflow_call:
    inputs:
      # Required Inputs
      ci_artifact:
        description: 'CI Artifact of file(s) to upload to S3'
        required: true
        type: string
      # Optional Inputs

jobs:
  s3_upload:
    runs-on: ubuntu-latest
    env:
      PUBLIC_DIR: public
    steps:
      # CI ARTIFACTS - Download Html/js/css files #
      - name: Download Web Bundle html/css/js - Artifacts
        uses: actions/download-artifact@v4
        with:
          # Artifact reference name (aka key) to download
          name: ${{ inputs.ci_artifact }}
          # Host local path to download the Artifact to
          path: ${{ env.PUBLIC_DIR }}

      ## S3 UPLOAD - Deploy to S3 Bucket ##
      - name: Deploy to S3 Bucket
        run: |
          docker run -t --rm -v $(pwd):/app -w /app \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            -e AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
            -e PUBLIC_DIR=$PUBLIC_DIR \
            amazon/aws-cli s3 sync $PUBLIC_DIR s3://$AWS_BUCKET_NAME --delete