name: End to End Tests
on:
  workflow_call:
    inputs:
      website_artifact:
        required: true
        type: string
        description: 'CI Artifact (id/alias) of uploaded Build Results'

jobs:
  browser:
    runs-on: ubuntu-latest
    name: ${{ matrix.browser }}
    container:
      image: cypress/included:cypress-12.17.3-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    strategy:
      matrix:
        browser: ["chrome", "edge", "firefox"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # CI ARTIFACTS - Download Html/js/css files #
      - name: Download Web Bundle html/css/js - Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.website_artifact }}
          path: build

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "UI Tests - ${{ matrix.browser }}"
        run: |
          npx -y http-server ./build -p 9000 &
          SERVER_PID=$!
          npx -y wait-on http://localhost:9000
          cd ./e2e && cypress run --browser ${{ matrix.browser }} --spec cypress/e2e/*.cy.js --config baseUrl=http://localhost:9000
          kill $SERVER_PID
