#############################
## PR to Boarding - GitOps ##
#############################

# export tt='board-request'; git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  push:
    tags:
      - board-request   # Request to be included in next Release
      - board-n-release  # Request to be included in next Release and create a Release

jobs:
  pr_to_boarding:
    uses: boromir674/automated-workflows/.github/workflows/go-pr-to-boarding.yml@v1.13.1
    with:
      # PR from <user_branch>  -->  <github.ref>-<user_branch>
      # board_tag becomes the first part of the new branch's name string
      board_tag: "${{ github.ref_name }}"
      main_branch: ${{ vars.MAIN_BRANCH || 'main' }}
    secrets:
      # 'GitHub Token, with permissions to create PRs and push to the repository'
      github_pat: ${{ secrets.SSG_GO_PR_TO_BOARDING }}
