name: Lighthouse Audit
on:
  workflow_call:
    inputs:
      # OPTIONAL
      target_ci_artifact:
        required: false
        type: string
        description: 'CI Artifact with static website to audit'
      target_url:
        required: false
        type: string
        description: 'URL to audit'
      # REQUIRED

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    env:
      RUNTIME_JSON: .lighthouseci/assertion-results.json
      GOLD_STANDARD_JSON: .lh-assertion-results-gs.json
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'

      # Install lhci
      - run: yarn global add @lhci/cli@0.14.x

      # Checkout code into dedicate 'code' subdirectory
      - uses: actions/checkout@v4
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: 'code'
      
      # Keep only Lighthouse-relevant config files
      # - run: |
      #     mv code/.lighthouserc.json .

      # Run Lighthouse CI

      # Healthcheck
      - run: lhci healthcheck

      - name: Derive Lighthouse CLI flags from inputs
        # if input url use --url and value
        # if input ci artifact, will will download and serve the artifact later
        # else exit with error msg and 1 exit code
        run: |
          if [ -n "${{ inputs.target_url }}" ]; then
            if [ -n "${{ inputs.target_ci_artifact }}" ]; then
              echo "ERROR: Both target_url and target_ci_artifact inputs are provided. Please provide only one."
              exit 1
            fi
            echo "AUDIT_TARGET=url=${{ inputs.target_url }}" >> $GITHUB_ENV
            echo "[INFO] Will audit URL: ${{ inputs.target_url }}"
          elif [ -n "${{ inputs.target_ci_artifact }}" ]; then
            echo "[INFO] Will donwload and serve Static Site from CI Artifacts"
            echo "SINGAL_ARTIFACT=true" >> $GITHUB_ENV
            echo "AUDIT_TARGET=staticDistDir ./public" >> $GITHUB_ENV
            echo "[INFO] Will audit Static Site from CI Artifact: ${{ inputs.target_ci_artifact }}"
          fi

      - name: 'Download Website bundle (files) from CI Artifact'
        if: env.SINGAL_ARTIFACT == 'true'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.target_ci_artifact }}
          path: public

      - name: "Audit Site run Assertions and capture exit code"
        # AUTORUN and write .lighthouseci/assertion-results.json in Step Summary
        run: |
          lhci autorun "--collect.${{ env.AUDIT_TARGET }}" --collect.numberOfRuns=1 || pass_all_assertions=0

          echo "## Lighthouse" >> $GITHUB_STEP_SUMMARY

          if [ $pass_all_assertions -eq 0 ]; then
            echo "[WARN] LHCI did not pass all default Lighthouse Assertions!"
            echo " - LHCI did not pass all default Lighthouse Assertions!" >> $GITHUB_STEP_SUMMARY
            echo ""  >> $GITHUB_STEP_SUMMARY

            echo "### Assertions Failed: Errors + Warnings" >> $GITHUB_STEP_SUMMARY
            echo test_echo1 >> $GITHUB_STEP_SUMMARY
            ls -la ${RUNTIME_JSON}
            echo "```json" >> $GITHUB_STEP_SUMMARY
            echo "$(cat ${RUNTIME_JSON})" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo test_echo2>> $GITHUB_STEP_SUMMARY

          else
            echo "[INFO] LHCI passed all default Lighthouse Assertions!"
            echo " - LHCI passed all default Lighthouse Assertions!" >> $GITHUB_STEP_SUMMARY
          fi

      # per .html audit reports in JSON and Html + assertion-results.json
      - run: ls -la ./.lighthouseci/
        if: always()

      # Upload
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./.lighthouseci/  # upload this folder
          name: lighthouseci  # under this Artifact name

      - uses: actions/checkout@v4
        if: always()
        with:
          # directory to clone into
          path: code

      - run: mv code/${{ env.GOLD_STANDARD_JSON }} .

      # - name: Runtime Creation of GS JSON file from developer
      #   if: always()
      #   run: |
      #     cat > ${GOLD_STANDARD_JSON} <<EOF
      #     [
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "errors-in-console",
      #         "level": "error",
      #         "url": "http://localhost:37821/404.html",
      #         "auditTitle": "Browser errors were logged to the console",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console/"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "html-has-lang",
      #         "level": "error",
      #         "url": "http://localhost:37821/404.html",
      #         "auditTitle": "`<html>` element does not have a `[lang]` attribute",
      #         "auditDocumentationLink": "https://dequeuniversity.com/rules/axe/4.9/html-has-lang"
      #       },
      #       {
      #         "name": "maxLength",
      #         "expected": 0,
      #         "actual": 1,
      #         "values": [
      #           1
      #         ],
      #         "operator": "<=",
      #         "passed": false,
      #         "auditId": "legacy-javascript",
      #         "level": "warn",
      #         "url": "http://localhost:37821/404.html",
      #         "auditTitle": "Avoid serving legacy JavaScript to modern browsers",
      #         "auditDocumentationLink": "https://web.dev/articles/publish-modern-javascript"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "meta-description",
      #         "level": "error",
      #         "url": "http://localhost:37821/404.html",
      #         "auditTitle": "Document does not have a meta description",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/seo/meta-description/"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "crawlable-anchors",
      #         "level": "error",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Links are not crawlable",
      #         "auditDocumentationLink": "https://support.google.com/webmasters/answer/9112205"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0.5,
      #         "values": [
      #           0.5
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "dom-size",
      #         "level": "warn",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Avoid an excessive DOM size",
      #         "auditDocumentationLink": "https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "errors-in-console",
      #         "level": "error",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Browser errors were logged to the console",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console/"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "heading-order",
      #         "level": "error",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Heading elements are not in a sequentially-descending order",
      #         "auditDocumentationLink": "https://dequeuniversity.com/rules/axe/4.9/heading-order"
      #       },
      #       {
      #         "name": "maxLength",
      #         "expected": 0,
      #         "actual": 2,
      #         "values": [
      #           2
      #         ],
      #         "operator": "<=",
      #         "passed": false,
      #         "auditId": "legacy-javascript",
      #         "level": "warn",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Avoid serving legacy JavaScript to modern browsers",
      #         "auditDocumentationLink": "https://web.dev/articles/publish-modern-javascript"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0.64,
      #         "values": [
      #           0.64
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "max-potential-fid",
      #         "level": "warn",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Max Potential First Input Delay",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/performance/lighthouse-max-potential-fid/"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "target-size",
      #         "level": "error",
      #         "url": "http://localhost:37821/index.html",
      #         "auditTitle": "Touch targets do not have sufficient size or spacing.",
      #         "auditDocumentationLink": "https://dequeuniversity.com/rules/axe/4.9/target-size"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "errors-in-console",
      #         "level": "error",
      #         "url": "http://localhost:37821/404/index.html",
      #         "auditTitle": "Browser errors were logged to the console",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console/"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "html-has-lang",
      #         "level": "error",
      #         "url": "http://localhost:37821/404/index.html",
      #         "auditTitle": "`<html>` element does not have a `[lang]` attribute",
      #         "auditDocumentationLink": "https://dequeuniversity.com/rules/axe/4.9/html-has-lang"
      #       },
      #       {
      #         "name": "maxLength",
      #         "expected": 0,
      #         "actual": 1,
      #         "values": [
      #           1
      #         ],
      #         "operator": "<=",
      #         "passed": false,
      #         "auditId": "legacy-javascript",
      #         "level": "warn",
      #         "url": "http://localhost:37821/404/index.html",
      #         "auditTitle": "Avoid serving legacy JavaScript to modern browsers",
      #         "auditDocumentationLink": "https://web.dev/articles/publish-modern-javascript"
      #       },
      #       {
      #         "name": "minScore",
      #         "expected": 0.9,
      #         "actual": 0,
      #         "values": [
      #           0
      #         ],
      #         "operator": ">=",
      #         "passed": false,
      #         "auditId": "meta-description",
      #         "level": "error",
      #         "url": "http://localhost:37821/404/index.html",
      #         "auditTitle": "Document does not have a meta description",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/seo/meta-description/"
      #       },
      #       {
      #         "name": "maxLength",
      #         "expected": 0,
      #         "actual": 1,
      #         "values": [
      #           1
      #         ],
      #         "operator": "<=",
      #         "passed": false,
      #         "auditId": "unused-javascript",
      #         "level": "error",
      #         "url": "http://localhost:37821/404/index.html",
      #         "auditTitle": "Reduce unused JavaScript",
      #         "auditDocumentationLink": "https://developer.chrome.com/docs/lighthouse/performance/unused-javascript/"
      #       }
      #     ]
      #     EOF

      # each json is an array of objects x, each x.auditId property is a unique ID of assertion
      # verify assertion-results.json and .ls-assertion-results-gs.json are the same
      # Verify Gold Standard Performance reached!'
      - name: 'Compare ${{ env.RUNTIME_JSON }} to ${{ env.GOLD_STANDARD_JSON }}'
        if: always()
        env:
          COMPARE: code/scripts/ci-compare-json-arrays.py
        run: |
          chmod +x ${{ env.COMPARE }}
          exit_code=0
          ${{ env.COMPARE }} ${{ env.RUNTIME_JSON }} ${{ env.GOLD_STANDARD_JSON }} || exit_code=1

          if [ $exit_code -eq 0 ]; then
            echo "[INFO] Lighthouse Job PASSED!"
            echo " - Lighthouse Job reached Gold Standard!" >> $GITHUB_STEP_SUMMARY
          else
            echo "[ERROR] Lighthouse Job FAILED!"
            echo " - Lighthouse Job did not reach Gold Standard!" >> $GITHUB_STEP_SUMMARY
          fi
          exit $exit_code
          

        # # use jq create two objects with keys being the x.auditId 
        # # then make sure all top-level properties/keys are the same (using jq) and
        # # and each object under the same top-level key is identical
        # run: |
        #   jq -s 'add | map({(.auditId): .}) | add' ${RUNTIME_JSON} > ${RUNTIME_JSON}.jq
        #   jq -s 'add | map({(.auditId): .}) | add' ${GOLD_STANDARD_JSON} > ${GOLD_STANDARD_JSON}.jq
        #   jq -n --argfile runtime ${RUNTIME_JSON}.jq --argfile gold_standard ${GOLD_STANDARD_JSON}.jq '$runtime == $gold_standard' || exit_code=1
