name: 'Test Minified Web Bundle'
on:
  workflow_call:
    inputs:
      # Required Inputs
      bundle_ci_artifact:
        description: 'CI Artifact Name for Web Bundle'
        required: true
        type: string
      bundle_size:
        description: "Expected Bundle Size on disk, computed by 'du -sh'"
        type: string
        required: true
      expected_number_of_files:
        description: 'Expected Number of Files in the Bundle, used for testing'
        type: number
        required: true
      # Optional Inputs
      bundle_size_acceptance:
        description: 'Max Bundle Size in MB'
        required: false
        type: number
        default: 3


jobs:
  test_bundle:
    runs-on: ubuntu-latest
    env:
      _BUNDLE_DIR: web_bundle
    steps:
      # CI ARTIFACTS - Download Web Bundle html/css/js ##
      - name: Download Web Bundle - Artifacts
        uses: actions/download-artifact@v4
        with:
          # Artifact reference name (aka key) to download
          name: ${{ inputs.bundle_ci_artifact }}
          # Host local path to download the Artifact to
          path: ${{ env._BUNDLE_DIR }}

      - name: Measure Bundle Size
        id: bundle_size

        # parse '2.7M  public' into '2.7M'
        run: echo BUNDLE_SIZE=$(du -sh "${{ env._BUNDLE_DIR }}" | cut -f1) >> $GITHUB_ENV

      - run: 'echo "*Bundle Size*: **${{ env.BUNDLE_SIZE }}**" >> $GITHUB_STEP_SUMMARY'

      - run: echo "BUNDLE_SIZE_IN_MB=$(echo '${{ env.BUNDLE_SIZE }}' | tr -d 'MB')" >> $GITHUB_ENV

      - run: echo "SIZE_VALUE=$(echo '${{ env.BUNDLE_SIZE_IN_MB }}' | tr ',' '.')" >> $GITHUB_ENV

      - name: 'Verify Bundle Size smaller than ${{ inputs.bundle_size_acceptance }} MB'
        run: |
          if [ $(bc <<< "${{ env.SIZE_VALUE }} > ${{ inputs.bundle_size_acceptance }}") -eq 1 ]; then
            echo "[ERROR] Bundle Size ${{ env.SIZE_VALUE }} is GREATER than ${{ inputs.bundle_size_acceptance }} MB!"
            echo "[INFO] Regression has happened! Exiting with status code 1"
            echo "**Regression has happend!**" >> $GITHUB_STEP_SUMMARY
            echo " - Bundle Size: **${{ env.SIZE_VALUE }} MB**" >> $GITHUB_STEP_SUMMARY
            echo "is bigger than" >> $GITHUB_STEP_SUMMARY
            echo " - Max Acceptable Bundle Size: **${{ inputs.bundle_size_acceptance }} MB**" >> $GITHUB_STEP_SUMMARY
            echo "'Automated Bundle Tests' **shall FAIL**" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "**Congrats!** Bundle Size did not exceed ${{ inputs.bundle_size_acceptance }} MB" >> $GITHUB_STEP_SUMMARY
          fi

      
      # Web bundle TESTS, assuming it is a gatsby SSR site of an SPA

# Expected bundle structure:
# drwxr-xr-x 2 runner docker   4096 Jul 14 11:00 404
# -rw-r--r-- 1 runner docker   1651 Jul 14 11:00 404.html
# -rw-r--r-- 1 runner docker  77070 Jul 14 11:00 app-f175f9ec0d19d7e24df4.js
# -rw-r--r-- 1 runner docker    246 Jul 14 11:00 app-f175f9ec0d19d7e24df4.js.LICENSE.txt
# -rw-r--r-- 1 runner docker 367591 Jul 14 11:00 app-f175f9ec0d19d7e24df4.js.map
# -rw-r--r-- 1 runner docker    226 Jul 14 11:00 chunk-map.json
# -rw-r--r-- 1 runner docker    753 Jul 14 11:00 component---src-pages-404-tsx-7bbe527623e6b0d1f8b0.js
# -rw-r--r-- 1 runner docker   1936 Jul 14 11:00 component---src-pages-404-tsx-7bbe527623e6b0d1f8b0.js.map
# -rw-r--r-- 1 runner docker 155436 Jul 14 11:00 component---src-pages-index-tsx-32438662074361ef743c.js
# -rw-r--r-- 1 runner docker 689753 Jul 14 11:00 component---src-pages-index-tsx-32438662074361ef743c.js.map
# -rw-r--r-- 1 runner docker 140364 Jul 14 11:00 framework-e07c0498098a9e84c9e8.js
# -rw-r--r-- 1 runner docker    721 Jul 14 11:00 framework-e07c0498098a9e84c9e8.js.LICENSE.txt
# -rw-r--r-- 1 runner docker 355292 Jul 14 11:00 framework-e07c0498098a9e84c9e8.js.map
# -rw-r--r-- 1 runner docker  38214 Jul 14 11:00 index.html
# drwxr-xr-x 6 runner docker   4096 Jul 14 11:00 page-data
# -rw-r--r-- 1 runner docker     99 Jul 14 11:00 robots.txt
# -rw-r--r-- 1 runner docker    389 Jul 14 11:00 sitemap.xml
# -rw-r--r-- 1 runner docker   3422 Jul 14 11:00 styles.c332001ae72ea32dc04e.css
# -rw-r--r-- 1 runner docker   4903 Jul 14 11:00 webpack-runtime-1646bdb5252b0d000de8.js
# -rw-r--r-- 1 runner docker  22910 Jul 14 11:00 webpack-runtime-1646bdb5252b0d000de8.js.map
# -rw-r--r-- 1 runner docker   1305 Jul 14 11:00 webpack.stats.json
# drwxr-xr-x 3 runner docker   4096 Jul 14 11:00 ~partytown

      # ls -l into the bundle directory
      - name: List Bundle Directory
        run: ls -l ${{ env._BUNDLE_DIR }}
      - run: ls -laR ${{ env._BUNDLE_DIR }}

      # Test 1: Verify standard files are present: index.html, sitemap.xml, etc
      - name: Verify index.html, sitemap.xml, robots.txt, webpack.stats.json, etc are present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -f index.html ]; then
            echo "[ERROR] index.html is missing!"
            exit 1
          fi
          if [ ! -f sitemap.xml ]; then
            echo "[ERROR] sitemap.xml is missing!"
            exit 1
          fi
          if [ ! -f robots.txt ]; then
            echo "[ERROR] robots.txt is missing!"
            exit 1
          fi
          if [ ! -f webpack.stats.json ]; then
            echo "[ERROR] webpack.stats.json is missing!"
            exit 1
          fi
          if [ ! -f chunk-map.json ]; then
            echo "[ERROR] chunk-map.json is missing!"
            exit 1
          fi
          if [ ! -f 404.html ]; then
            echo "[ERROR] 404.html is missing!"
            exit 1
          fi

      # Test 2: Verify the presence of the main bundle files
      - name: Verify main bundle files are present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -f app-*.js ]; then
            echo "[ERROR] app-*.js is missing!"
            exit 1
          fi
          if [ ! -f framework-*.js ]; then
            echo "[ERROR] framework-*.js is missing!"
            exit 1
          fi
          if [ ! -f styles.*.css ]; then
            echo "[ERROR] styles.*.css is missing!"
            exit 1
          fi
          if [ ! -f webpack-runtime-*.js ]; then
            echo "[ERROR] webpack-runtime-*.js is missing!"
            exit 1
          fi

      # Test 3: Verify the presence of the page-data directory
      - name: Verify page-data directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d page-data ]; then
            echo "[ERROR] page-data directory is missing!"
            exit 1
          fi

      # [INFO]: Static Directory may or may not exist
      - name: Check if static directory exists
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          echo "## Static Directory" >> $GITHUB_STEP_SUMMARY
          if [ ! -d static ]; then
            echo "[INFO] 'static' directory isn't present."
            echo "Directory \`static\` isn't present in the bundle" >> $GITHUB_STEP_SUMMARY
          else
            echo "[INFO] 'static' directory is present."
            echo "Directory \`static\` is present in the bundle" >> $GITHUB_STEP_SUMMARY
          fi

      # Test 5: Verify the presence of the 404 directory
      - name: Verify 404 directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d 404 ]; then
            echo "[ERROR] 404 directory is missing!"
            exit 1
          fi

      # Test 6: Verify the presence of the ~partytown directory
      - name: Verify ~partytown directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d '~partytown' ]; then
            echo "[ERROR] ~partytown directory is missing!"
            exit 1
          fi

      # Strict Sanity Check for all expected files
      # find Directory_name -ls
      - name: 'Sanity Check that exactly ${{ inputs.expected_number_of_files }} files are included in the bundle'
        run: |
          NB_FILES=$(find ${{ env._BUNDLE_DIR }} -type f -ls | wc -l)
          echo "[INFO] Number of Files in Bundle: $NB_FILES"
          echo " - Number of Files in Web Bundle: **${NB_FILES}**" >> $GITHUB_STEP_SUMMARY

          if [ $NB_FILES -ne ${{ inputs.expected_number_of_files }} ]; then
            echo "[ERROR] Found ${NB_FILES} files in web bundle, but ${{ inputs.expected_number_of_files }} are expected"
            echo "exiting with status code 1"
            exit 1
          fi
