name: 'Test Minified Web Bundle'
on:
  workflow_call:
    inputs:
      # Required Inputs
      bundle_ci_artifact:
        description: 'CI Artifact Name for Web Bundle'
        required: true
        type: string
      bundle_size:
        description: "Expected Bundle Size, computed by 'du -sh'"
        type: string
        required: true
      # Optional Inputs
      bundle_size_acceptance:
        description: 'Max Bundle Size in MB'
        required: false
        type: number
        default: 3


jobs:
  test_bundle:
    runs-on: ubuntu-latest
    env:
      _BUNDLE_DIR: web_bundle
    steps:
      # Verify Bundle Size is lower than 3MB
      # eg parse 2,6M /data/repos/static-site-generator/public-auto
      - name: Verify Reported Bundle Size smaller than ${{ inputs.bundle_size_acceptance }}MB
        run: |
          echo "[INFO] Bundle Size: ${{ inputs.bundle_size }}"
          _bundle_size=$(echo "${{ inputs.bundle_size }}" | cut -d' ' -f1)
          echo "[DEBUG] Bundle Size: $_bundle_size"
          if [ $(echo "$_bundle_size" | tr -d 'M') -gt 3 ]; then
            echo "[ERROR] Bundle Size is GREATER than 3MB!"
            echo "exiting with status code 1"
            exit 1
          else
            echo "[INFO] Bundle Size is LESS than 3MB"
          fi

      # CI ARTIFACTS - Download Web Bundle html/css/js ##
      - name: Download Web Bundle - Artifacts
        uses: actions/download-artifact@v4
        with:
          # Artifact reference name (aka key) to download
          name: ${{ inputs.bundle_ci_artifact }}
          # Host local path to download the Artifact to
          path: ${{ env._BUNDLE_DIR }}
      
      # Web bundle TESTS, assuming it is a gatsby SSR site of an SPA

# Expected bundle structure:
# drwxrwxrwx 1 root root      0 Jun 29 16:46  404
# -rwxrwxrwx 1 root root   1769 Jun 29 16:46  404.html
# -rwxrwxrwx 1 root root  87132 Jun 29 16:46  app-a0858404f12ca10a33dd.js
# -rwxrwxrwx 1 root root    246 Jun 29 16:46  app-a0858404f12ca10a33dd.js.LICENSE.txt
# -rwxrwxrwx 1 root root 414141 Jun 29 16:46  app-a0858404f12ca10a33dd.js.map
# -rwxrwxrwx 1 root root    275 Jun 29 16:46  chunk-map.json
# -rwxrwxrwx 1 root root    761 Jun 29 16:46  component---src-pages-404-tsx-37e9974fe7ddd09a4d26.js
# -rwxrwxrwx 1 root root   1936 Jun 29 16:46  component---src-pages-404-tsx-37e9974fe7ddd09a4d26.js.map
# -rwxrwxrwx 1 root root 170681 Jun 29 16:46  component---src-pages-index-tsx-51cc0fb0b2bf08eb2f7c.js
# -rwxrwxrwx 1 root root 734923 Jun 29 16:46  component---src-pages-index-tsx-51cc0fb0b2bf08eb2f7c.js.map
# -rwxrwxrwx 1 root root 140799 Jun 29 16:46  framework-81a8cf24be6209802093.js
# -rwxrwxrwx 1 root root    721 Jun 29 16:46  framework-81a8cf24be6209802093.js.LICENSE.txt
# -rwxrwxrwx 1 root root 355920 Jun 29 16:46  framework-81a8cf24be6209802093.js.map
# -rwxrwxrwx 1 root root  38332 Jun 29 16:46  index.html
# drwxrwxrwx 1 root root   4096 Jun 29 16:46  page-data
# drwxrwxrwx 1 root root   4096 Jun 29 16:46 '~partytown'
# -rwxrwxrwx 1 root root  85042 Jun 29 16:46  polyfill-6534e443b1457de06b09.js
# -rwxrwxrwx 1 root root 208013 Jun 29 16:46  polyfill-6534e443b1457de06b09.js.map
# -rwxrwxrwx 1 root root     99 Jun 29 16:46  robots.txt
# -rwxrwxrwx 1 root root    389 Jun 29 16:46  sitemap.xml
# drwxrwxrwx 1 root root      0 Jun 29 16:46  static
# -rwxrwxrwx 1 root root   3422 Jun 29 16:46  styles.c332001ae72ea32dc04e.css
# -rwxrwxrwx 1 root root   4997 Jun 29 16:46  webpack-runtime-70a38c66ba5dcf943ed0.js
# -rwxrwxrwx 1 root root  23340 Jun 29 16:46  webpack-runtime-70a38c66ba5dcf943ed0.js.map
# -rwxrwxrwx 1 root root   1652 Jun 29 16:46  webpack.stats.json

      # ls -l into the bundle directory
      - name: List Bundle Directory
        working-directory: ${{ env._BUNDLE_DIR }}
        run: ls -l

      # Test 1: Verify standard files are present: index.html, sitemap.xml, etc
      - name: Verify index.html, sitemap.xml, robots.txt, webpack.stats.json, etc are present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -f index.html ]; then
            echo "[ERROR] index.html is missing!"
            exit 1
          fi
          if [ ! -f sitemap.xml ]; then
            echo "[ERROR] sitemap.xml is missing!"
            exit 1
          fi
          if [ ! -f robots.txt ]; then
            echo "[ERROR] robots.txt is missing!"
            exit 1
          fi
          if [ ! -f webpack.stats.json ]; then
            echo "[ERROR] webpack.stats.json is missing!"
            exit 1
          fi
          if [ ! -f chunk-map.json ]; then
            echo "[ERROR] chunk-map.json is missing!"
            exit 1
          fi
          if [ ! -f 404.html ]; then
            echo "[ERROR] 404.html is missing!"
            exit 1
          fi

      # Test 2: Verify the presence of the main bundle files
      - name: Verify main bundle files are present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -f app-*.js ]; then
            echo "[ERROR] app-*.js is missing!"
            exit 1
          fi
          if [ ! -f framework-*.js ]; then
            echo "[ERROR] framework-*.js is missing!"
            exit 1
          fi
          if [ ! -f polyfill-*.js ]; then
            echo "[ERROR] polyfill-*.js is missing!"
            exit 1
          fi
          if [ ! -f styles-*.css ]; then
            echo "[ERROR] styles-*.css is missing!"
            exit 1
          fi
          if [ ! -f webpack-runtime-*.js ]; then
            echo "[ERROR] webpack-runtime-*.js is missing!"
            exit 1
          fi

      # Test 3: Verify the presence of the page-data directory
      - name: Verify page-data directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d page-data ]; then
            echo "[ERROR] page-data directory is missing!"
            exit 1
          fi

      # Test 4: Verify the presence of the static directory
      - name: Verify static directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d static ]; then
            echo "[ERROR] static directory is missing!"
            exit 1
          fi

      # Test 5: Verify the presence of the 404 directory
      - name: Verify 404 directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d 404 ]; then
            echo "[ERROR] 404 directory is missing!"
            exit 1
          fi

      # Test 6: Verify the presence of the ~partytown directory
      - name: Verify ~partytown directory is present
        working-directory: ${{ env._BUNDLE_DIR }}
        run: |
          if [ ! -d '~partytown' ]; then
            echo "[ERROR] ~partytown directory is missing!"
            exit 1
          fi
